### ISSUE TITLE
ASR stop unexpected issue

### ISSUE THREAD

**Issue by JeanTracker** [nugu-developers/nugu-linux#187] opened 2020-02-25 03:46 UTC
## Issue

This is an issue where a user's new conversation stops unexpected. This issue occurs when a user attempts a new conversation at the end of the music they were listening to.

## How to Reproduce
1. execute the example `nugu_sample`
2. press the command: `l` (start listening)
```
=======================================================
NUGU SDK Command (Connected)
=======================================================
w : start wakeup
l : start listening
s : stop listening
t : text input
m : set mic mute
c : connect
d : disconnect
q : quit
-------------------------------------------------------
Select Command > l
```
3. speak the word `라디오 들려줘`
4. speak the wakeup word `아리아` at the end of the song
    you can see the duration in the 'PlaybackStarted' event and position as belows.
```
Event
{
  "context": {
   "client" : {
      "wakeupWord" : "아리아"
   },
   "supportedInterfaces" : {
      "AudioPlayer" : {
         "durationInMilliseconds" : 365000,
         "offsetInMilliseconds" : 0,
         "playerActivity" : "PLAYING",
         "token" : "10/Play/recommend/0",
         "version" : "1.1"
      }
   }
}
,
  "event": {
    "header": {
      "referrerDialogRequestId": "08737c84b401ff3b4dbec48c271b7861",
      "dialogRequestId": "0873a10daa01ff3b4dbec48ccfd2a4be",
      "messageId": "0873a10daa01ff3b4dbec48c8beaf4cd",
      "name": "PlaybackStarted",
      "namespace": "AudioPlayer",
      "version": "1.1"
    },
    "payload": {
   "offsetInMilliseconds" : "0",
   "playServiceId" : "com.classic.manger",
   "token" : "10/Play/recommend/0"
}

  }
}
...
[AudioPlayer] - position: 1
[AudioPlayer] - position: 2
```

## Analysis
1. Send Event `AudioPlayer.PlaybackFinished` at the end of music playback
2.Wakeup word detected and sent Event `ASR.Recognize`
3. Wait for user's communication
4. Receive new music playback Directive `AudioPlayer.Play`
5. Focus request from AudioPlayerAgent
6. Release focus on ASRAgent
7. Recognize mode canceled on ASRAgent

## Log
find the word `[ASR] LISTENING` in the log and you can easily analysis the issue.
```
02-25 02:49:13.286  3185  3185 I <audio_player_agent.cc:874> [audioplayer state] PAUSED -> PLAYING
[AudioPlayer] PLAYING
02-25 02:49:13.350  3185  3200 D [CURL] Recv data: 472 bytes
02-25 02:49:13.350  3185  3200 I <-- Directives
{
   "directives" : [
      {
         "header" : {
            "dialogRequestId" : "087389dd0a01ff3b4dbec48c4cea4b5f",
            "messageId" : "087389dd600193cc1b858351e15edf4c",
            "name" : "NoDirectives",
            "namespace" : "System",
            "referrerDialogRequestId" : "087389c21801ff3b4dbec48c5cd007d7",
            "timestamp" : {
               "dialogRequestId" : "2020-02-25T11:49:13.226+09:00",
               "messageId" : "2020-02-25T11:49:13.312+09:00"
            },
            "version" : "1.0"
         },
         "payload" : {}
      }
   ]
}

[AudioPlayer] - position: 470
02-25 02:49:13.351  3185  3200 D <v1_directives.cc:198> group={ "directives": ["System.NoDirectives"] }
02-25 02:49:13.351  3185  3185 D <nugu_directive_sequencer.c:52> added: System.NoDirectives 'id=087389dd600193cc1b858351e15edf4c'
02-25 02:49:13.351  3185  3185 D <capability_manager.cc:226> send directive_dialog_id with 087389dd0a01ff3b4dbec48c4cea4b5f
02-25 02:49:13.351  3185  3185 D <nugu_directive_sequencer.c:81> remain directives: 0
02-25 02:49:13.351  3185  3185 I <nugu_directive.c:87> destroy: System.NoDirectives 'id=087389dd600193cc1b858351e15edf4c'
02-25 02:49:14.345  3185  3185 D <gstreamer.c:124> Discovered 'https://die4l7zpbzx5k.cloudfront.net/album/aac/UCCW-3010-3/01.m4a'
02-25 02:49:14.345  3185  3185 D <gstreamer.c:150> duration: 535, seekable: 1
02-25 02:49:14.345  3185  3185 D <gstreamer.c:153> [gstreamer]Duration: 0:08:55.247000000
02-25 02:49:14.345  3185  3185 D <audio_player_agent.cc:903> LOADING_MEDIA_SUCCESS
...
[AudioPlayer] - position: 533
[AudioPlayer] - position: 534
02-25 02:50:18.445  3185  3185 D <gstreamer.c:230> GST_MESSAGE_EOS
02-25 02:50:18.465  3185  3185 D <audio_player_agent.cc:906> PLAYING_MEDIA_FINISHED
02-25 02:50:18.465  3185  3185 I <nugu_focus.c:287> FOCUS-RELEASE: name=cap_audio (type=MEDIA)
02-25 02:50:18.465  3185  3185 I <nugu_focus.c:168> ON-UN-FOCUS: name=cap_audio (type=MEDIA)
02-25 02:50:18.465  3185  3185 I <nugu_focus.c:309>  - return REMOVE: remove focus item
02-25 02:50:18.465  3185  3185 D <nugu_focus.c:55> Focus length = 0 (empty)
02-25 02:50:18.465  3185  3185 D <nugu_focus.c:321> nugu_focus_release() done
02-25 02:50:18.465  3185  3185 D <system_agent.cc:137> update timer
02-25 02:50:18.465  3185  3185 D <http2_request.c:244> request(0x6150000e1d00) created
02-25 02:50:18.466  3185  3200 D [CURL] Found bundle for host stg-gw02-http.sktnugu.com: 0x604000040110 [can multiplex]
02-25 02:50:18.466  3185  3200 D [CURL] Multiplexed connection found!
02-25 02:50:18.466  3185  3200 D [CURL] Found connection 0, with 1 requests on it
02-25 02:50:18.466  3185  3200 D [CURL] Re-using existing connection! (#0) with host stg-gw02-http.sktnugu.com
02-25 02:50:18.466  3185  3200 D [CURL] Using Stream ID: 1ab (easy handle 0x62200009c100)
02-25 02:50:18.466  3185  3200 D [CURL] Send header: POST /v1/event HTTP/2
Host: stg-gw02-http.sktnugu.com
user-agent: OpenSDK/1.0.0 (Linux) Client/0.6.0
accept: */*
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjM3MjEwMTg3ODQsInVzZXJfbmFtZSI6IkFMREY1VDFTRjY5Q0VBREFBNUNCIiwianRpIjoiMmVhMzY0YTgtZDJjMi00MmM2LThmY2YtZjg3OGRkZjYzNzUxIiwiY2xpZW50X2lkIjoic3BlYWtlci5udWd1Lm51MTEwIiwic2NvcGUiOltdLCJleHQiOnsidXNyIjoiQUxERjVUMVNGNjlDRUFEQUE1Q0IiLCJwb2MiOiJzcGVha2VyLm51Z3UubnUxMTAiLCJkdmMiOiJBTERGSDNGQlhYUzI5QTJFOUQ2NiIsInRrbiI6IkRDMTE0NDYzMTA0MzQ5NzM5RTMyRTM1REQ0NEVBOUJBIn19.tPxewqXAN6Rqr7Oy5IMdvCVu6Ez9MZA027bmSJW6mzg

02-25 02:50:18.466  3185  3200 D <http2_request.c:158> Sent req(0x6150000e1d00) 788 bytes
02-25 02:50:18.466  3185  3200 I --> Event
{
  "context": {
   "client" : {
      "wakeupWord" : "아리아"
   },
   "supportedInterfaces" : {
      "AudioPlayer" : {
         "durationInMilliseconds" : 535000,
         "offsetInMilliseconds" : 534000,
         "playerActivity" : "FINISHED",
         "token" : "4/Play/recommend/0",
         "version" : "1.1"
      }
   }
}
,
  "event": {
    "header": {
      "referrerDialogRequestId": "08737c84b401ff3b4dbec48c271b7861",
      "dialogRequestId": "08738adbe101ff3b4dbec48c2c10dc3f",
      "messageId": "08738adbe101ff3b4dbec48c02decb19",
      "name": "PlaybackFinished",
      "namespace": "AudioPlayer",
      "version": "1.1"
    },
    "payload": {
   "offsetInMilliseconds" : "534000",
   "playServiceId" : "com.classic.manger",
   "token" : "4/Play/recommend/0"
}

  }
}
02-25 02:50:18.466  3185  3200 D [CURL] Send data: 788 bytes
02-25 02:50:18.467  3185  3185 I <audio_player_agent.cc:874> [audioplayer state] PLAYING -> FINISHED
[AudioPlayer] FINISHED
02-25 02:50:18.467  3185  3185 D <gstreamer.c:194> State set to PLAYING -> PAUSED
02-25 02:50:18.469  3185  3185 D <gstreamer.c:194> State set to PAUSED -> READY
02-25 02:50:18.476  3185  3200 D [CURL] Recv header: HTTP/2 200
02-25 02:50:18.476  3185  3200 D [CURL] Recv header: date: Tue, 25 Feb 2020 02:50:18 GMT
02-25 02:50:18.476  3185  3200 D [CURL] Recv header: set-cookie: SCOUTER=x5ldev5vktekqi; Path=/; Expires=Sun, 14-Mar-2088 06:04:25 GMT; Max-Age=2147483647
02-25 02:50:18.476  3185  3200 D [CURL] Recv header: expires: Thu, 01 Jan 1970 00:00:00 GMT
02-25 02:50:18.476  3185  3200 D [CURL] Recv header: server: devicegateway-server
02-25 02:50:18.476  3185  3200 D [CURL] Recv header: content-type: text/plain;charset=iso-8859-1
02-25 02:50:18.476  3185  3200 D [CURL] Recv header:
02-25 02:50:18.476  3185  3200 D [CURL] Recv data: 3 bytes
02-25 02:50:18.477  3185  3200 D <http2_network.c:193> completed req(0x6150000e1d00) (code=200)
02-25 02:50:18.477  3185  3200 D <http2_request.c:253> req(0x6150000e1d00) destroy
02-25 02:50:18.591  3185  3185 D <wakeup_handler.cc:66> WakeupState::DETECTED
[Wakeup] wakeup detected
02-25 02:50:18.591  3185  3185 D <audio_recorder_manager.cc:173> stop recorder: 0x60b0000432d0, list's size: 0
02-25 02:50:18.710  3185  3200 D [CURL] Recv data: 1228 bytes
02-25 02:50:18.711  3185  3200 I <-- Directives
{
   "directives" : [
      {
         "header" : {
            "dialogRequestId" : "08738adbe101ff3b4dbec48c2c10dc3f",
            "messageId" : "08738adcc901ff3b4dbec48c45d27c91",
            "name" : "Play",
            "namespace" : "AudioPlayer",
            "referrerDialogRequestId" : "08737c84b401ff3b4dbec48c271b7861",
            "timestamp" : {
               "dialogRequestId" : "2020-02-25T11:50:18.465+09:00",
               "messageId" : "2020-02-25T11:50:18.697+09:00"
            },
            "version" : "1.0"
         },
         "payload" : {
            "audioItem" : {
               "metadata" : {
                  "template" : {
                     "content" : {
                        "imageUrl" : "https://die4l7zpbzx5k.cloudfront.net/images/artists/m/1225.png",
                        "subtitle1" : "Giordano, Umberto",
                        "subtitle2" : "Played by Gigli, Beniamino",
                        "title" : "안드레아 세니에 "
                     },
                     "title" : {
                        "iconUrl" : "https://die4l7zpbzx5k.cloudfront.net/icon/cm_BI_50px.png",
                        "text" : "추천 클래식"
                     },
                     "type" : "AudioPlayer.Template1"
                  }
               },
               "stream" : {
                  "expectedPreviousToken" : "4/Play/recommend/0",
                  "offsetInMilliseconds" : 0,
                  "progressReport" : {
                     "progressReportDelayInMilliseconds" : 0,
                     "progressReportIntervalInMilliseconds" : 0
                  },
                  "token" : "5/Play/recommend/0",
                  "url" : "https://die4l7zpbzx5k.cloudfront.net/album/aac/7699962/10.m4a"
               }
            },
            "playServiceId" : "com.classic.manger",
            "playStackControl" : {
               "playServiceId" : "com.classic.manger",
               "type" : "PUSH"
            }
         }
      }
   ]
}

02-25 02:50:18.712  3185  3200 D <v1_directives.cc:198> group={ "directives": ["AudioPlayer.Play"] }
02-25 02:50:18.780  3185  3185 D <portaudio.c:286> stop done
02-25 02:50:18.780  3185  3185 D <asr_agent.cc:218> startRecognition()
02-25 02:50:18.780  3185  3185 I <nugu_focus.c:220> FOCUS-REQUEST: name=asr (type=ASR)
02-25 02:50:18.780  3185  3185 I <nugu_focus.c:159> ON-FOCUS: name=asr (type=ASR)
02-25 02:50:18.780  3185  3185 D <asr_agent.cc:57> ASRFocusListener::onFocus
02-25 02:50:18.780  3185  3185 D <asr_agent.cc:484> ListeningState::READY
02-25 02:50:18.780  3185  3185 D <system_agent.cc:137> update timer
02-25 02:50:18.781  3185  3185 D <http2_request.c:244> request(0x615000132980) created
02-25 02:50:18.781  3185  3198 D <speech_recognizer.cc:126> Listening Thread: asr_is_running=1
02-25 02:50:18.781  3185  3185 D <nugu_focus.c:59> Focus length = 1
02-25 02:50:18.781  3185  3185 D <nugu_focus.c:65> 	[0] asr        (1:ASR       )
02-25 02:50:18.781  3185  3200 D [CURL] Found bundle for host stg-gw02-http.sktnugu.com: 0x604000040110 [can multiplex]
02-25 02:50:18.781  3185  3200 D [CURL] Multiplexed connection found!
02-25 02:50:18.781  3185  3200 D [CURL] Found connection 0, with 1 requests on it
02-25 02:50:18.781  3185  3185 D <nugu_focus.c:231> nugu_focus_request() done
02-25 02:50:18.781  3185  3200 D [CURL] Re-using existing connection! (#0) with host stg-gw02-http.sktnugu.com
02-25 02:50:18.782  3185  3185 D <nugu_directive_sequencer.c:52> added: AudioPlayer.Play 'id=08738adcc901ff3b4dbec48c45d27c91'
02-25 02:50:18.782  3185  3185 D <capability_manager.cc:226> send directive_dialog_id with 08738adbe101ff3b4dbec48c2c10dc3f
02-25 02:50:18.782  3185  3185 D <audio_player_agent.cc:268> message: {
   "audioItem" : {
      "metadata" : {
         "template" : {
            "content" : {
               "imageUrl" : "https://die4l7zpbzx5k.cloudfront.net/images/artists/m/1225.png",
               "subtitle1" : "Giordano, Umberto",
               "subtitle2" : "Played by Gigli, Beniamino",
               "title" : "안드레아 세니에 "
            },
            "title" : {
               "iconUrl" : "https://die4l7zpbzx5k.cloudfront.net/icon/cm_BI_50px.png",
               "text" : "추천 클래식"
            },
            "type" : "AudioPlayer.Template1"
         }
      },
      "stream" : {
         "expectedPreviousToken" : "4/Play/recommend/0",
         "offsetInMilliseconds" : 0,
         "progressReport" : {
            "progressReportDelayInMilliseconds" : 0,
            "progressReportIntervalInMilliseconds" : 0
         },
         "token" : "5/Play/recommend/0",
         "url" : "https://die4l7zpbzx5k.cloudfront.net/album/aac/7699962/10.m4a"
      }
   },
   "playServiceId" : "com.classic.manger",
   "playStackControl" : {
      "playServiceId" : "com.classic.manger",
      "type" : "PUSH"
   }
}

02-25 02:50:18.782  3185  3199 D <audio_recorder_manager.cc:173> stop recorder: 0x60b0000432d0, list's size: 0
02-25 02:50:18.782  3185  3199 D <portaudio.c:271> already stop
02-25 02:50:18.782  3185  3200 D [CURL] Using Stream ID: 1ad (easy handle 0x622000079900)
02-25 02:50:18.782  3185  3185 D <playsync_manager.cc:53>
>>>>> (ContextStack) >>>>>
[com.classic.manger] AudioPlayer,
<<<<< (ContextStack) <<<<<

02-25 02:50:18.782  3185  3185 D <audio_player_agent.cc:558> = token: 5/Play/recommend/0
02-25 02:50:18.782  3185  3185 D <audio_player_agent.cc:559> = url: https://die4l7zpbzx5k.cloudfront.net/album/aac/7699962/10.m4a
02-25 02:50:18.782  3185  3185 D <audio_player_agent.cc:560> = offset: 0
02-25 02:50:18.782  3185  3185 D <audio_player_agent.cc:561> = report_delay_time: 0
02-25 02:50:18.782  3185  3185 D <audio_player_agent.cc:562> = report_interval_time: 0
02-25 02:50:18.782  3185  3185 D <media_player.cc:256> request to stop mediaplayer
02-25 02:50:18.783  3185  3200 D [CURL] Send header: POST /v1/event HTTP/2
Host: stg-gw02-http.sktnugu.com
user-agent: OpenSDK/1.0.0 (Linux) Client/0.6.0
accept: */*
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjM3MjEwMTg3ODQsInVzZXJfbmFtZSI6IkFMREY1VDFTRjY5Q0VBREFBNUNCIiwianRpIjoiMmVhMzY0YTgtZDJjMi00MmM2LThmY2YtZjg3OGRkZjYzNzUxIiwiY2xpZW50X2lkIjoic3BlYWtlci5udWd1Lm51MTEwIiwic2NvcGUiOltdLCJleHQiOnsidXNyIjoiQUxERjVUMVNGNjlDRUFEQUE1Q0IiLCJwb2MiOiJzcGVha2VyLm51Z3UubnUxMTAiLCJkdmMiOiJBTERGSDNGQlhYUzI5QTJFOUQ2NiIsInRrbiI6IkRDMTE0NDYzMTA0MzQ5NzM5RTMyRTM1REQ0NEVBOUJBIn19.tPxewqXAN6Rqr7Oy5IMdvCVu6Ez9MZA027bmSJW6mzg

02-25 02:50:18.783  3185  3200 D <http2_request.c:158> Sent req(0x615000132980) 1398 bytes
02-25 02:50:18.783  3185  3200 I --> Event
{
  "context": {
   "client" : {
      "playStack" : [ "com.classic.manger" ],
      "wakeupWord" : "아리아"
   },
   "supportedInterfaces" : {
      "ASR" : {
         "version" : "1.0"
      },
      "AudioPlayer" : {
         "durationInMilliseconds" : 535000,
         "offsetInMilliseconds" : 534000,
         "playerActivity" : "FINISHED",
         "token" : "4/Play/recommend/0",
         "version" : "1.1"
      },
      "Mic" : {
         "micStatus" : "ON",
         "version" : "1.0"
      },
      "Speaker" : {
         "version" : "1.0",
         "volumes" : [
            {
               "maxVolume" : 100,
               "minVolume" : 0,
               "muted" : false,
               "name" : "NUGU",
               "volume" : 100
            }
         ]
      },
      "System" : {
         "version" : "1.1"
      },
      "TTS" : {
         "engine" : "skt",
         "ttsActivity" : "FINISHED",
         "version" : "1.0"
      },
      "Text" : {
         "version" : "1.0"
      }
   }
}
,
  "event": {
    "header": {
      "dialogRequestId": "08738add1c01ff3b4dbec48c2a56ec5d",
      "messageId": "08738add1c01ff3b4dbec48cc85903f5",
      "name": "Recognize",
      "namespace": "ASR",
      "version": "1.0"
    },
    "payload": {
   "codec" : "SPEEX",
   "encoding" : "COMPLETE",
   "endpointing" : "CLIENT",
   "language" : "KOR",
   "property" : "NORMAL"
}

  }
}
02-25 02:50:18.784  3185  3200 D [CURL] Send data: 1398 bytes
02-25 02:50:18.784  3185  3185 D <media_player.cc:222> request to set source(https://die4l7zpbzx5k.cloudfront.net/album/aac/7699962/10.m4a) mediaplayer
02-25 02:50:18.784  3185  3185 D <gstreamer.c:477> playurl:https://die4l7zpbzx5k.cloudfront.net/album/aac/7699962/10.m4a
02-25 02:50:18.784  3185  3185 D <media_player.cc:421> media state changed(STOPPED -> PREPARE)
02-25 02:50:18.785  3185  3185 D <media_player.cc:286> request to seek(0) mediaplayer
02-25 02:50:18.785  3185  3185 D <gstreamer.c:618> seek is reserved (0 sec)
02-25 02:50:18.785  3185  3185 I <nugu_focus.c:220> FOCUS-REQUEST: name=cap_audio (type=MEDIA)
02-25 02:50:18.785  3185  3185 D <nugu_focus.c:59> Focus length = 1
02-25 02:50:18.785  3185  3185 D <nugu_focus.c:65> 	[0] asr        (1:ASR       )
02-25 02:50:18.785  3185  3185 I <nugu_focus.c:180> ON-STEAL-FOCUS: name=asr (type=ASR)
02-25 02:50:18.785  3185  3185 I <nugu_focus.c:185>  - ALLOW
02-25 02:50:18.785  3185  3185 I <nugu_focus.c:168> ON-UN-FOCUS: name=asr (type=ASR)
02-25 02:50:18.785  3185  3185 D <asr_agent.cc:68> ASRFocusListener::onUnfocus
02-25 02:50:18.785  3185  3185 D <audio_recorder_manager.cc:173> stop recorder: 0x60b000041280, list's size: 0
02-25 02:50:18.785  3185  3185 D <portaudio.c:271> already stop
[ASR] IDLE
02-25 02:50:18.785  3185  3185 D <wakeup_handler.cc:60> WakeupState::DETECTING
[Wakeup] wakeup detecting...
02-25 02:50:18.785  3185  3185 D <nugu_focus.c:245> return REMOVE: remove focus item
02-25 02:50:18.785  3185  3185 I <nugu_focus.c:159> ON-FOCUS: name=cap_audio (type=MEDIA)
02-25 02:50:18.785  3185  3185 D <media_player.cc:246> request to play mediaplayer
02-25 02:50:18.785  3185  3185 D <gstreamer.c:657> volume: 1.000000
02-25 02:50:18.791  3185  3198 D <audio_recorder_manager.cc:154> start recorder: 0x60b000041280
02-25 02:50:18.791  3185  3198 D <portaudio.c:223> rec - 3200, 50
02-25 02:50:18.796  3185  3200 D [CURL] Recv header: HTTP/2 200
02-25 02:50:18.797  3185  3200 D [CURL] Recv header: date: Tue, 25 Feb 2020 02:50:18 GMT
02-25 02:50:18.797  3185  3200 D [CURL] Recv header: set-cookie: SCOUTER=x7d268ljtg03s0; Path=/; Expires=Sun, 14-Mar-2088 06:04:25 GMT; Max-Age=2147483647
02-25 02:50:18.797  3185  3200 D [CURL] Recv header: expires: Thu, 01 Jan 1970 00:00:00 GMT
02-25 02:50:18.797  3185  3200 D [CURL] Recv header: server: devicegateway-server
02-25 02:50:18.797  3185  3200 D [CURL] Recv header: content-type: text/plain;charset=iso-8859-1
02-25 02:50:18.797  3185  3200 D [CURL] Recv header:
02-25 02:50:18.797  3185  3200 D [CURL] Recv data: 3 bytes
02-25 02:50:18.797  3185  3200 D <http2_network.c:193> completed req(0x615000132980) (code=200)
02-25 02:50:18.797  3185  3200 D <http2_request.c:253> req(0x615000132980) destroy
02-25 02:50:18.978  3185  3185 D <nugu_focus.c:59> Focus length = 1
02-25 02:50:18.978  3185  3185 D <nugu_focus.c:65> 	[0] cap_audio  (5:MEDIA     )
02-25 02:50:18.978  3185  3185 D <nugu_focus.c:261> nugu_focus_request() done
02-25 02:50:18.978  3185  3185 D <nugu_directive_sequencer.c:81> remain directives: 0
02-25 02:50:18.978  3185  3185 I <nugu_directive.c:87> destroy: AudioPlayer.Play 'id=08738adcc901ff3b4dbec48c45d27c91'
02-25 02:50:18.978  3185  3185 D <wakeup_handler.cc:74> WakeupState::DONE
02-25 02:50:18.979  3185  3198 D <portaudio.c:260> start done
02-25 02:50:18.979  3185  3185 D <asr_agent.cc:501> ListeningState::LISTENING
[ASR] LISTENING
02-25 02:50:18.979  3185  3198 D <audio_recorder_manager.cc:173> stop recorder: 0x60b000041280, list's size: 0
02-25 02:50:18.979  3185  3185 D <gstreamer.c:194> State set to NULL -> READY
02-25 02:50:19.207  3185  3198 D <portaudio.c:286> stop done
02-25 02:50:19.208  3185  3185 D <asr_agent.cc:550> ListeningState::DONE
[ASR] onCancel
02-25 02:50:19.208  3185  3185 I <nugu_focus.c:287> FOCUS-RELEASE: name=asr (type=ASR)
02-25 02:50:19.208  3185  3185 D <nugu_focus.c:59> Focus length = 1
02-25 02:50:19.208  3185  3185 D <nugu_focus.c:65> 	[0] cap_audio  (5:MEDIA     )
02-25 02:50:19.208  3185  3185 D <nugu_focus.c:301> nugu_focus_release() done
02-25 02:50:19.979  3185  3185 D <gstreamer.c:245> Buffering (  1%)
02-25 02:50:20.357  3185  3185 D <gstreamer.c:245> Buffering (  2%)
02-25 02:50:20.560  3185  3185 D <gstreamer.c:245> Buffering (  4%)
02-25 02:50:22.633  3185  3185 D <gstreamer.c:245> Buffering (100%)
02-25 02:50:22.635  3185  3537 D <gstreamer.c:280> Received new source pad 'src_10' <--- 'audio_source#0':
02-25 02:50:22.636  3185  3185 D <gstreamer.c:124> Discovered 'https://die4l7zpbzx5k.cloudfront.net/album/aac/7699962/10.m4a'
02-25 02:50:22.636  3185  3185 D <gstreamer.c:150> duration: 140, seekable: 1
02-25 02:50:22.636  3185  3185 D <gstreamer.c:153> [gstreamer]Duration: 0:02:20.514000000
02-25 02:50:22.636  3185  3185 D <media_player.cc:421> media state changed(PREPARE -> READY)
[AudioPlayer] - duration: 140
02-25 02:50:22.637  3185  3185 D <audio_player_agent.cc:903> LOADING_MEDIA_SUCCESS
02-25 02:50:22.736  3185  3537 D <gstreamer.c:311> Link succeeded (type 'audio/x-raw').
02-25 02:50:22.764  3185  3185 D <gstreamer.c:194> State set to READY -> PAUSED
02-25 02:50:22.765  3185  3185 D <gstreamer.c:194> State set to PAUSED -> PLAYING
02-25 02:50:22.766  3185  3185 D <media_player.cc:421> media state changed(READY -> PLAYING)
02-25 02:50:22.766  3185  3185 D <system_agent.cc:137> update timer
02-25 02:50:22.766  3185  3185 D <http2_request.c:244> request(0x61500010d400) created
02-25 02:50:22.766  3185  3185 I <audio_player_agent.cc:874> [audioplayer state] IDLE -> PLAYING
[AudioPlayer] PLAYING
02-25 02:50:22.767  3185  3200 D [CURL] Found bundle for host stg-gw02-http.sktnugu.com: 0x604000040110 [can multiplex]
02-25 02:50:22.767  3185  3200 D [CURL] Multiplexed connection found!
02-25 02:50:22.767  3185  3200 D [CURL] Found connection 0, with 1 requests on it
02-25 02:50:22.767  3185  3200 D [CURL] Re-using existing connection! (#0) with host stg-gw02-http.sktnugu.com
02-25 02:50:22.768  3185  3200 D [CURL] Using Stream ID: 1af (easy handle 0x622000040900)
02-25 02:50:22.768  3185  3200 D [CURL] Send header: POST /v1/event HTTP/2
Host: stg-gw02-http.sktnugu.com
user-agent: OpenSDK/1.0.0 (Linux) Client/0.6.0
accept: */*
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjM3MjEwMTg3ODQsInVzZXJfbmFtZSI6IkFMREY1VDFTRjY5Q0VBREFBNUNCIiwianRpIjoiMmVhMzY0YTgtZDJjMi00MmM2LThmY2YtZjg3OGRkZjYzNzUxIiwiY2xpZW50X2lkIjoic3BlYWtlci5udWd1Lm51MTEwIiwic2NvcGUiOltdLCJleHQiOnsidXNyIjoiQUxERjVUMVNGNjlDRUFEQUE1Q0IiLCJwb2MiOiJzcGVha2VyLm51Z3UubnUxMTAiLCJkdmMiOiJBTERGSDNGQlhYUzI5QTJFOUQ2NiIsInRrbiI6IkRDMTE0NDYzMTA0MzQ5NzM5RTMyRTM1REQ0NEVBOUJBIn19.tPxewqXAN6Rqr7Oy5IMdvCVu6Ez9MZA027bmSJW6mzg

02-25 02:50:22.768  3185  3200 D <http2_request.c:158> Sent req(0x61500010d400) 776 bytes
02-25 02:50:22.768  3185  3200 I --> Event
{
  "context": {
   "client" : {
      "wakeupWord" : "아리아"
   },
   "supportedInterfaces" : {
      "AudioPlayer" : {
         "durationInMilliseconds" : 140000,
         "offsetInMilliseconds" : 0,
         "playerActivity" : "PLAYING",
         "token" : "5/Play/recommend/0",
         "version" : "1.1"
      }
   }
}
,
  "event": {
    "header": {
      "referrerDialogRequestId": "08737c84b401ff3b4dbec48c271b7861",
      "dialogRequestId": "08738aecae01ff3b4dbec48cdb137f60",
      "messageId": "08738aecae01ff3b4dbec48c311d1727",
      "name": "PlaybackStarted",
      "namespace": "AudioPlayer",
      "version": "1.1"
    },
    "payload": {
   "offsetInMilliseconds" : "0",
   "playServiceId" : "com.classic.manger",
   "token" : "5/Play/recommend/0"
}

  }
}
02-25 02:50:22.768  3185  3200 D [CURL] Send data: 776 bytes
02-25 02:50:22.779  3185  3200 D [CURL] Recv header: HTTP/2 200
02-25 02:50:22.779  3185  3200 D [CURL] Recv header: date: Tue, 25 Feb 2020 02:50:22 GMT
02-25 02:50:22.779  3185  3200 D [CURL] Recv header: set-cookie: SCOUTER=x27fn6r17d3jgk; Path=/; Expires=Sun, 14-Mar-2088 06:04:29 GMT; Max-Age=2147483647
02-25 02:50:22.779  3185  3200 D [CURL] Recv header: expires: Thu, 01 Jan 1970 00:00:00 GMT
02-25 02:50:22.779  3185  3200 D [CURL] Recv header: server: devicegateway-server
02-25 02:50:22.779  3185  3200 D [CURL] Recv header: content-type: text/plain;charset=iso-8859-1
02-25 02:50:22.779  3185  3200 D [CURL] Recv header:
02-25 02:50:22.779  3185  3200 D [CURL] Recv data: 3 bytes
02-25 02:50:22.779  3185  3200 D <http2_network.c:193> completed req(0x61500010d400) (code=200)
02-25 02:50:22.779  3185  3200 D <http2_request.c:253> req(0x61500010d400) destroy
02-25 02:50:22.917  3185  3200 D [CURL] Recv data: 472 bytes
02-25 02:50:22.918  3185  3200 I <-- Directives
{
   "directives" : [
      {
         "header" : {
            "dialogRequestId" : "08738aecae01ff3b4dbec48cdb137f60",
            "messageId" : "08738aed3501ac3d038fb4448c5749e6",
            "name" : "NoDirectives",
            "namespace" : "System",
            "referrerDialogRequestId" : "08737c84b401ff3b4dbec48c271b7861",
            "timestamp" : {
               "dialogRequestId" : "2020-02-25T11:50:22.766+09:00",
               "messageId" : "2020-02-25T11:50:22.901+09:00"
            },
            "version" : "1.0"
         },
         "payload" : {}
      }
   ]
}

02-25 02:50:22.918  3185  3200 D <v1_directives.cc:198> group={ "directives": ["System.NoDirectives"] }
02-25 02:50:22.918  3185  3185 D <nugu_directive_sequencer.c:52> added: System.NoDirectives 'id=08738aed3501ac3d038fb4448c5749e6'
02-25 02:50:22.918  3185  3185 D <capability_manager.cc:226> send directive_dialog_id with 08738aecae01ff3b4dbec48cdb137f60
02-25 02:50:22.918  3185  3185 D <nugu_directive_sequencer.c:81> remain directives: 0
02-25 02:50:22.918  3185  3185 I <nugu_directive.c:87> destroy: System.NoDirectives 'id=08738aed3501ac3d038fb4448c5749e6'
[AudioPlayer] - position: 1
[AudioPlayer] - position: 2
```

**Comment by kimhyungrok** [comment] 2020-02-25 04:40
I can't reproduce this issue. Is It 100% occur? My trial is below. (I try 3 times.)

1. playing classic manager (duration : 111)
2. At playing end position (position : 111), try to wake-up and voice command
3. It's handled normally.

```
[AudioPlayer] - position: 111
[AudioPlayer] FINISHED
[AudioPlayer] - duration: 335
[AudioPlayer] PLAYING
_[Wakeup] wakeup detected_
[AudioPlayer] PAUSED
_[ASR] LISTENING_
_[ASR] RECOGNIZING_
_[ASR] BUSY_
_[ASR] onComplete > 날씨_
[TTS] PLAYING..., dialog_id: 0873eab12201e3c3c73ae1346a61134e
_[ASR] IDLE_
[Wakeup] wakeup detecting...
[TTS] TEXT > 잘 못 들었어요., dialog_id: 0873eab12201e3c3c73ae1346a61134e
```

**Comment by JeanTracker** [comment] 2020-02-25 05:14
It looks timing issue.
The NUGU SDK can receive the directive `AudioPlayer.Play` in response to event `AudioPlayer.PlaybackFinished`, which may cause delays depending on network conditions.
If a wakeup occurs during this period and the ASRAgent has focus first, the issue will occur.

**Comment by kimhyungrok** [comment] 2020-02-27 08:11
## Cause

During the ASR has focus, if AudioPlayer received some directive, it steal focus from asr, because the current asr focus steal policy is NUGU_FOCUS_STEAL_ALLOW. As a result, the listening is stopped abnormally.

- Approximate Flow

```
[ASR] listening
[AudioPlayer] receive play directive
[AudioPlayer] request focus
[ASR] focus steal allow
[AudioPlayer] onFocus
[ASR] unFocus
[ASR] listening stopped 
```

## Solution

It fix to allow to steal ASR focus only ListeningState is done.

**Comment by kimhyungrok** [comment] 2020-02-27 08:13
please review, when #199 PR is merged.

**Closed** 2020-02-27 09:17 UTC
Labels: bug
